### ISSUE TITLE
EDL

### ISSUE THREAD

**Issue by Rafaustino** [fsantanna/EDL#3]

**Comment by fsantanna** [comment]
?

**Comment by Rafaustino** [comment]
Achei que era assim que habilitava o ISSUES, professor. Não estou conseguindo habilitar 

Enviado do meu iPhone

**Comment by fsantanna** [comment]
Você viu o link no aviso de 08/03?

**Comment by Rafaustino** [comment]
Vi mas não entendi muito bem, professor

Enviado do meu iPhone

**Comment by fsantanna** [comment]
Não entendeu o que exatamente?

**Comment by Rafaustino** [comment]
consegui, obrigado

2016-03-15 14:31 GMT-03:00 fsantanna notifications@github.com:
