### ISSUE TITLE
Trabalho 02

### ISSUE THREAD

**Issue by Rafaustino** [fsantanna/EDL#6]
Boa tarde, professor! Gostaria de pedir a ajuda do senhor. Não entendi muito bem o que tenho que fazer. Fiz o download do arquivo mas depois o que tenho que fazer? Muito obrigado pela atenção. Grato, Rafael Faustino

**Comment by fsantanna** [comment]
- Instalar o programa (Love)
- Executar um exemplo qualquer
- Fazer um screenshot do exemplo executando
- Subir o código e o screenshot para cá

**Comment by Rafaustino** [comment]
bom dia, professor!  Acabei de fazer isso que o senhor mandou! Obrigado pela ajuda
