### ISSUE TITLE
Repositório do trabalho-03 (Joguinho)

### ISSUE THREAD

**Issue by yagotome** [fsantanna/EDL#7]
Boa tarde, professor!

Até então, os trabalhos que fizemos têm sido colocados no diretório trabalhos/trabalho-XX.

No entanto, o trabalho-03 é um trabalho em grupo. Então, pensei em criar um repositório separado, onde cada integrante do grupo fosse um contribuidor. E vi que é possível usar "submodules" em git para que em nossos forks de EDL tenham inclusos o repositório a parte do jogo.

Segue um exemplo do que estou falando. Supondo que o repositório A seja o nosso fork de EDL e B seria o do jogo (trabalho-02).

https://github.com/yagotome/A

O que você acha?

Tem alguma forma melhor de fazermos isto?

**Comment by fsantanna** [comment]
Acho uma boa ideia criar um repositório separado e adicionar todos os integrantes como "contributors".

**Comment by Rafaustino** [comment]
Boa tarde, professor! Enviei o trabalho do jogo em Love2D na quinta feira, mas não consegui criar um diretório para o jogo. É o arquivo main.lua! Reparei tbm que não tem a nota de apresentação do trabalho-01, desde já grato, Rafael Faustino!! 

Enviado do meu iPhone
